### PR TITLE
Added MIT licence

### PR DESCRIPTION
**Pull request by redfast00**

### CODE REVIEW

**Comment by redfast00** [comment]
Can you please give permission to change the licence from nothing to MIT?

- [ ] @rien 
- [ ] @Silox 
- [ ] @Procrat 
- [ ] @tivervac 
- [ ] @werthen 
- [ ] @feliciaan 
- [ ] @Robbe7730 
- [ ] @VandorpeDavid 
- [ ] @ninewise 
- [ ] @wpinnoo 
- [ ] @wschella

**Comment by Silox** [comment]
Just do it?

**Comment by werthen** [comment]
Afaik the introduction of a license does not do anything retroactively, so your MIT license now doesn't need any approval of previous contributors

**Comment by feliciaan** [comment]
Ok. 

Sent from my iPhone

**Comment by Procrat** [comment]
I hereby declare that I transfer all ownership of all code that I have written thus far for this Git repository to Zeus WPI, for them to license under any open source software license as they see fit, as long as its kind is approved by the [Open Source Initiative](https://opensource.org/licenses).

I love the initiative btw! Good job!

**Comment by ninewise** [comment]
@werthen, true, but I think by asking they can retroactively change the license to something more open. If they don't, the license only applies to the new code and the old code would remain non-free.

**Comment by VandorpeDavid** [comment]
I hereby declare that I transfer all ownership of all code that I have written thus far for this Git repository to Zeus WPI, for them to license under any open source software license as they see fit, as long as its kind is approved by the Open Source Initiative.

I love the initiative btw! Good job!

**Comment by redfast00** [comment]
@wpinnoo can you please approve this licence change or give a reason why you don't approve it?

**Comment by wpinnoo** [comment]
I approve!

**Comment by redfast00** [comment]
Everyone who contributed code approved of this licence change, so merging it in!

**Pull request merged**
