### PR TITLE
Mo security, mo better

### PR DESCRIPTION
**Pull request by redfast00**

### CODE REVIEW

**Comment by redfast00** [comment]
@rien I'd like to add CSP, but am afraid that something would break. Maybe we should look into reporting failures (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only)

**Comment by rien** [comment]
@redfast00 if stuff breaks, we can easily undo the breakage? CSP is not cached I think.

**Comment by redfast00** [comment]
Yes, but maybe we can have a trial period with reporting-only to check if things will break?

**Comment by rien** [comment]
Fine by me :)

**Comment by redfast00** [comment]
don't merge yet, in progress

**Pull request merged**
